### ISSUE TITLE
error :(

### ISSUE THREAD

**Issue by thunder-red-star** [thunder-red-star/fbla-lessons#1]
```
CssSyntaxError: <css input>:1:1: Unknown word
    at Input.error (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\postcss\lib\input.js:148:16)
    at Parser.unknownWord (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\postcss\lib\parser.js:540:22)
    at Parser.other (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\postcss\lib\parser.js:164:12)
    at Parser.parse (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\postcss\lib\parser.js:72:16)
    at parse (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\postcss\lib\parse.js:11:12)
    at new LazyResult (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\postcss\lib\lazy-result.js:133:16)
    at Processor.process (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\postcss\lib\processor.js:28:14)
    at Function.fromCSS (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\@marp-team\marpit\lib\theme.js:115:26)
    at ThemeSet.add (C:\Users\wlv13\WebstormProjects\fbla-lessons\node_modules\@marp-team\marpit\lib\theme_set.js:111:34)
    at file:///C:/Users/wlv13/WebstormProjects/fbla-lessons/compiler.mjs:17:16 {
  reason: 'Unknown word',
  source: '[object Object]',
  line: 1,
  column: 1,
  endLine: 1,
  endColumn: 2,
  input: {
    line: 1,
    column: 1,
    endLine: 1,
    endColumn: 2,
    source: '[object Object]'
  }
}

```

**Comment by thunder-red-star** [comment]
fixed thank :)
